package com.yinkun.creams.model;

import com.yinkun.creams.model.base.BaseFloor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Floor extends BaseFloor<Floor> {
	public static final Floor dao = new Floor().dao();
}
