package com.yinkun.creams.model;

import com.yinkun.creams.model.base.BasePark;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Park extends BasePark<Park> {
	public static final Park dao = new Park().dao();
}
