package com.yinkun.creams.model;

import com.yinkun.creams.model.base.BaseRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Room extends BaseRoom<Room> {
	public static final Room dao = new Room().dao();
}
